const projectData = [
  /*
  {
    name:'',
    tech:[''],
    intro:'',
    description:'',
    collaboration:'',
    deployment:'',
    repo:'',
    imgSrc: '',
  },
  */

  {
    name:'Klime',
    tech:['React Native', 'Cypress'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'6 (3 front end, 3 back end)',
    deployment:'https://qr.expo.dev/eas-update?updateId=4c187546-35cb-48f4-b8c6-6681cae70ad4&appScheme=exp&host=u.expo.dev',
    repo:'https://github.com/Jade-ZS/klime_fe',
  },
  {
    name:'Outfit Forecast',
    tech:['React', 'Cypress', 'CI', 'CSS', 'HTML'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'solo',
    deployment:'outfit-forecast.vercel.app',
    repo:'https://github.com/Jade-ZS/Outfit_Forecast',
  },
  {
    name:'Boardgame Gathering',
    tech:['React, PWA, Cypress, CSS, HTML'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'https://pwa-stretch.vercel.app/',
    repo:'https://github.com/Jade-ZS/Boardgame_Gathering',
  },
  {
    name:'Rancid Tomatillos',
    tech:['React, Cypress, CSS, HTML'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'rancid-tomatillos-topaz.vercel.app',
    repo:'https://github.com/Jade-ZS/rancid_tomatillos',
  },
  {
    name:'What\'s Cookin',
    tech:['JavaScript', 'HTML', 'CSS', , 'Unit Testing', 'Mocha', 'Chai'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/whats-cookin',
  },
  {
    name:'Self Care Center',
    tech:['JavaScript', 'HTML', 'CSS'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/self-care-center',
  },
  {
    name:'Overlook Hotel Management',
    tech:['JavaScript', 'HTML', 'CSS', 'Unit Testing', 'Mocha', 'Chai'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/overlook-hotel-management',
  },
  {
    name:'Rock Paper Scissors',
    tech:['JavaScript', 'HTML', 'CSS'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/Rock-Paper-Scissors',
  },
  {
    name:'ColoRandom',
    tech:['JavaScript', 'HTML', 'CSS'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/coloRandom-project',
  },
  {
    name:'RomCom',
    tech:['JavaScript', 'HTML', 'CSS'],
    intro:'',
    imgSrc: require('../../Assets/profile.JPG'),
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh nisl condimentum id venenatis a condimentum vitae. Integer quis auctor elit sed vulputate mi sit amet mauris. ',
    collaboration:'',
    deployment:'',
    repo:'https://github.com/Jade-ZS/romcom',
  },
  
];